// Server-rendered Worker pages. Existing management forms and API actions are retained.
export function renderAdmin({ user, projects, selected, builds, users, view, buildId }, forms) {
  const esc = value => String(value ?? '').replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]);
  const url = (page, id = '') => '/?view=' + page + '&project=' + encodeURIComponent(selected?.id || '') + (id ? '&build=' + encodeURIComponent(id) : '');
  const editable = ['admin', 'dev'].includes(user.role);
  const latest = builds[0];
  const titles = { dashboard: 'Dashboard', projects: 'Projects', builds: 'Builds', upload: 'Upload build', build: 'Build details', settings: 'Settings', logs: 'Logs' };
  if (!titles[view]) view = 'dashboard';
  const table = (items, paginate = true) => `<div class="table-wrap"><table ${paginate ? 'data-paginate' : ''}><thead><tr><th>Version</th><th>Channel</th><th>Build ID</th><th class="optional">Commit</th><th>Size</th><th>Status</th><th></th></tr></thead><tbody>${items.map(build => `<tr data-channel="${esc(build.channel)}" data-status="${esc(build.status)}"><td><a class="link-btn" href="${url('build', build.id)}"><strong>${esc(build.version)}</strong></a><div class="mono">${esc(build.created_at?.slice(0, 10))}</div></td><td>${esc(build.channel)}</td><td class="mono">${esc(build.id)}</td><td class="mono optional" title="${esc(build.commit_sha)}">${esc(build.commit_sha?.slice(0, 7) || '—')}</td><td>${(Number(build.total_size || 0) / 1073741824).toFixed(2)} GB</td><td><span class="badge state ${esc(build.status)}">${['assigned', 'stored', 'manifest-ready'].includes(build.status) ? 'Ready' : esc(build.status)}</span></td><td><button type="button" class="btn secondary small" data-menu="actions-${esc(build.id)}" aria-label="Actions for build ${esc(build.version)}">···</button><div class="action-menu" popover id="actions-${esc(build.id)}"><a href="${url('build', build.id)}">View details</a><button type="button" data-copy="${esc(build.id)}">Copy build ID</button>${build.download_url ? `<button type="button" data-copy="${esc(build.download_url)}">Copy download link</button>` : ''}<a href="/builds/${encodeURIComponent(build.id)}/manifest" target="_blank" rel="noopener">Open manifest</a>${editable ? `<form method="post" action="/builds/${encodeURIComponent(build.id)}/delete" data-confirm="Delete build ${esc(build.version)} and its files? This cannot be undone."><button class="danger" type="submit">Delete build</button></form>` : ''}</div></td></tr>`).join('') || '<tr><td colspan="7" class="empty"><strong>No builds uploaded</strong>Upload your first internal build.</td></tr>'}</tbody></table></div>`;
  let content = '';
  if (view === 'projects') content = `<div class="project-grid">${projects.map(project => `<section class="surface"><div class="surface-body"><h2>${esc(project.name)}</h2><p class="mono">${esc(project.bundle_id)}</p><a class="btn secondary section-gap" href="/?project=${encodeURIComponent(project.id)}&view=settings">Manage project →</a></div></section>`).join('')}${user.role === 'admin' ? `<section class="panel">${forms.createProjectForm()}</section>` : ''}</div>`;
  else if (!selected) content = '<section class="surface empty"><strong>No project selected</strong>Create a project to start managing builds.</section>';
  else if (view === 'builds') content = `<section class="surface"><div class="surface-header"><div><h2>Build history</h2><p>Review versions and manage test channels.</p></div><span class="mono">${builds.length} builds</span></div>${table(builds)}</section>`;
  else if (view === 'upload') content = editable ? `<div class="upload-layout">${forms.uploadPanel(user, selected)}</div>` : '<section class="surface empty">You do not have upload access.</section>';
  else if (view === 'settings') content = `<section class="panel">${forms.projectManagement(user, selected, builds, latest)}</section>${user.role === 'admin' ? forms.userAccess(users, user) : ''}`;
  else if (view === 'logs') content = '<section class="surface empty"><strong>Log storage is not connected</strong>This Worker does not currently provide a tester log API. Log management is available in the Flask dashboard.</section>';
  else if (view === 'build') {
    const build = builds.find(item => item.id === buildId);
    content = build ? `<nav class="tabs"><a href="#overview">Overview</a><a href="#changelog">Changelog</a><a href="#manifest">Manifest</a></nav><section class="surface" id="overview"><div class="surface-header"><h2>Build ${esc(build.version)}</h2><button class="btn secondary small" data-copy="${esc(build.id)}" type="button">Copy build ID</button></div><div class="surface-body"><dl class="detail-grid">${[['Build ID', build.id], ['Channel', build.channel], ['Commit', build.commit_sha], ['Uploaded', build.uploaded_at], ['Uploaded by', build.uploaded_by], ['Package size', (Number(build.total_size || 0) / 1073741824).toFixed(2) + ' GB'], ['Storage path', build.storage_path]].map(([label, value]) => `<div><dt>${label}</dt><dd>${esc(value || '—')}</dd></div>`).join('')}</dl></div></section><section class="surface section-gap" id="changelog"><div class="surface-header"><h2>Changelog and actions</h2></div><div class="surface-body">${forms.buildCard(user, build)}</div></section><section class="surface section-gap" id="manifest"><div class="surface-header"><h2>Manifest</h2><a class="link-btn" href="/builds/${encodeURIComponent(build.id)}/manifest" target="_blank" rel="noopener">Open full manifest ↗</a></div><div class="surface-body"><details><summary>Inspect files and hashes</summary><pre class="code-block">${esc(JSON.stringify(build.manifest, null, 2))}</pre></details></div></section>` : '<section class="surface empty">Build not found. Return to build history.</section>';
  } else content = `<section class="surface project-summary"><div><p class="eyebrow">Current project</p><h2>${esc(selected.name)}</h2><p>${esc(selected.description || selected.bundle_id)}</p></div><div class="latest-build"><div><p class="eyebrow">Latest build</p><strong>${esc(latest?.version || '—')}</strong><p>${esc(latest?.channel || 'No builds yet')}</p></div>${latest ? `<a class="btn secondary" href="${url('build', latest.id)}">View build →</a>` : ''}</div></section><div class="stat-strip"><span><strong>${builds.length}</strong> retained builds</span><span><strong>${(builds.reduce((sum, build) => sum + Number(build.total_size || 0), 0) / 1073741824).toFixed(2)} GB</strong> build packages</span></div><section class="surface"><div class="surface-header"><div><h2>Recent builds</h2><p>Latest versions available for testing.</p></div><a class="link-btn" href="${url('builds')}">View all →</a></div>${table(builds.slice(0, 6), false)}</section>`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Build Producer Dashboard</title>${forms.style()}</head><body><div class="shell"><aside class="sidebar"><a class="brand" href="/"><div class="brand-mark">BM</div><div><strong>Build Manager</strong><span>Internal workspace</span></div></a><label><span class="sidebar-label">Current project</span><select data-project-selector aria-label="Current project">${projects.map(project => `<option value="${esc(project.id)}" ${project.id === selected?.id ? 'selected' : ''}>${esc(project.name)}</option>`).join('')}</select></label><nav class="nav" aria-label="Main navigation">${[['dashboard', 'Dashboard'], ['projects', 'Projects'], ['builds', 'Builds'], ['logs', 'Logs'], ['settings', 'Settings']].map(([key, label]) => `<a class="${key === view || (key === 'builds' && ['build', 'upload'].includes(view)) ? 'active' : ''}" href="${url(key)}">${label}</a>`).join('')}</nav><div class="sidebar-spacer"></div><div class="account"><div><strong>${esc(user.email)}</strong><span>${esc(user.role)} access</span></div><form method="post" action="/logout"><button class="btn secondary">Sign out</button></form></div></aside><main class="main"><header class="topbar"><div><p class="eyebrow">Workspace / ${esc(selected?.name || 'Projects')}</p><h1>${titles[view]}</h1><p>Builds and test evidence, in one place.</p></div><div class="actions">${selected && editable && view !== 'upload' ? `<a class="btn" href="${url('upload')}">＋ Upload build</a>` : ''}<button class="icon-btn" type="button" data-theme-toggle aria-label="Switch color theme">◐</button></div></header>${content}</main></div></body></html>`;
}
